In [36]:
import pandas as pd
from sqlalchemy import create_engine

Store CSV into DataFrame

In [37]:
csv_file1 = "../Resources/winemag-data130.csv"
csv_file2 = "../Resources/winemag-data150.csv"
wine_data_data130_df = pd.read_csv(csv_file1, encoding="UTF-8")
wine_data_data150_df = pd.read_csv(csv_file2)
wine_data_data130_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [38]:
wine_data_data150_df["variety"].unique

<bound method Series.unique of 0         Cabernet Sauvignon
1              Tinta de Toro
2            Sauvignon Blanc
3                 Pinot Noir
4         Provence red blend
                 ...
150925           White Blend
150926       Champagne Blend
150927           White Blend
150928       Champagne Blend
150929          Pinot Grigio
Name: variety, Length: 150930, dtype: object>

In [39]:
wine_data_data130_df.loc[wine_data_data130_df["variety"]=="Heitz has made this stellar rosÃ© from the rare Grignolino grape since 1961. Ruby grapefruit-red, it's sultry with strawberry, watermelon, orange zest and salty spice flavor, highlighted with vibrant floral aromas.",:]

Empty DataFrame
Columns: [Unnamed: 0, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

In [40]:
# Create a filtered dataframe from specific columns
premises_cols= ["country","province","region_1","winery","designation","variety","title","points","price","description",]
wine_130_ts= wine_data_data130_df[premises_cols].copy()

# Rename the column headers
wine_130_ts=wine_130_ts.rename(columns={"description":"review",
                                        "designation":"vineyard",
                                        "region_1":"region"
                                       })


wine_130_ts

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Mosel,NaN,Dr. H. Thanisch (Erben Müller-Burggraef),Brauneberger Juffer-Sonnenuhr Spätlese,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,90,28.0,Notes of honeysuckle and cantaloupe sweeten th...
129967,US,Oregon,Oregon,Citation,NaN,Pinot Noir,Citation 2004 Pinot Noir (Oregon),90,75.0,Citation is given as much as a decade of bottl...
129968,France,Alsace,Alsace,Domaine Gresser,Kritt,Gewürztraminer,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,90,30.0,Well-drained gravel soil gives this wine its c...
129969,France,Alsace,Alsace,Domaine Marcel Deiss,NaN,Pinot Gris,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),90,32.0,"A dry style of Pinot Gris, this is crisp with ..."
129970,France,Alsace,Alsace,Domaine Schoffit,Lieu-dit Harth Cuvée Caroline,Gewürztraminer,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,90,21.0,"Big, rich and off-dry, this is powered by inte..."

In [41]:
# Create a filtered dataframe from specific columns
premises_cols2= ["country","province","region_1","winery","designation","variety","points","price","description"]
wine_150_ts= wine_data_data150_df[premises_cols2].copy()

# Rename the column headers
wine_150_ts=wine_150_ts.rename(columns={"description":"review",
                                        "designation":"vineyard",
                                        "region_1":"region"
                                       })

wine_150_ts

,country,province,region,winery,vineyard,variety,points,price,review
0,US,California,Napa Valley,Heitz,Martha's Vineyard,Cabernet Sauvignon,96,235.0,This tremendous 100% varietal wine hails from ...
1,Spain,Northern Spain,Toro,Bodega Carmen Rodríguez,Carodorum Selección Especial Reserva,Tinta de Toro,96,110.0,"Ripe aromas of fig, blackberry and cassis are ..."
2,US,California,Knights Valley,Macauley,Special Selected Late Harvest,Sauvignon Blanc,96,90.0,Mac Watson honors the memory of a wine once ma...
3,US,Oregon,Willamette Valley,Ponzi,Reserve,Pinot Noir,96,65.0,"This spent 20 months in 30% new French oak, an..."
4,France,Provence,Bandol,Domaine de la Bégude,La Brûlade,Provence red blend,95,66.0,"This is the top wine from La Bégude, named aft..."
...,...,...,...,...,...,...,...,...,...
150925,Italy,Southern Italy,Fiano di Avellino,Feudi di San Gregorio,NaN,White Blend,91,20.0,Many people feel Fiano represents southern Ita...
150926,France,Champagne,Champagne,H.Germain,Cuvée Prestige,Champagne Blend,91,27.0,"Offers an intriguing nose with ginger, lime an..."
150927,Italy,Southern Italy,Fiano di Avellino,Terredora,Terre di Dora,White Blend,91,20.0,This classic example comes from a cru vineyard...
150928,France,Champagne,Champagne,Gosset,Grand Brut Rosé,Champagne Blend,90,52.0,"A perfect salmon shade, with scents of peaches..."
150929,Italy,Northeastern Italy,Alto Adige,Alois Lageder,NaN,Pinot Grigio,90,15.0,More Pinot Grigios should taste like this. A r...

In [42]:
merged_df=wine_130_ts.merge(wine_150_ts, how="outer")

pd.set_option('display.max_columns', None)
merged_df

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
233942,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233943,Portugal,Port,NaN,Casa Santa Eufemia,30-year old tawny,Port,NaN,84,NaN,Oreo eaters will enjoy the aromas of this wine...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [43]:
duplicates = merged_df.loc[merged_df.duplicated(['review','country'])].sort_values('country')
duplicates

,country,province,region,winery,vineyard,variety,title,points,price,review
152515,Albania,Mirditë,NaN,Arbëri,NaN,Kallmet,NaN,88,20.0,This garnet-colored wine made from 100% Kallme...
233814,Argentina,Mendoza Province,Uco Valley,Cabra Montes,NaN,Chardonnay,NaN,86,9.0,"Fresh, tropical, and welcoming. Sweet and lush..."
165169,Argentina,Mendoza Province,Mendoza,Nieto Senetiner,Reserva,Torrontés,NaN,80,11.0,"Shows barely any color and then a hard, vapid,..."
165170,Argentina,Mendoza Province,Mendoza,Nieto Senetiner,Reserva,Torrontés,NaN,80,11.0,"Shows barely any color and then a hard, vapid,..."
165178,Argentina,Mendoza Province,Mendoza,Viniterra,Serie Terra Spakling,Malbec,NaN,80,14.0,Red in color and flat in terms of bubbles and ...
...,...,...,...,...,...,...,...,...,...,...
46273,NaN,NaN,NaN,Orbelus,Hrumki Melnik 55 Mourvèdre Marselan,Red Blend,Orbelus 2012 Hrumki Melnik 55 Mourvèdre Marsel...,89,25.0,An interesting blend of indigenous Bulgarian a...
83277,NaN,NaN,NaN,Gotsa Family Wines,Dry Unfiltered Rkatsiteli Mtsvane,White Blend,Gotsa Family Wines 2015 Dry Unfiltered Rkatsit...,88,25.0,"Amber to the eye, this wine features an entici..."
126113,NaN,NaN,NaN,Neumeister,Steirische Klassik,Gelber Muskateller,Neumeister 2016 Steirische Klassik Gelber Musk...,92,21.0,"A lively whiff of white blossom, Muscat grapes..."
203998,NaN,NaN,NaN,Chilcas,Piedra Feliz,Pinot Noir,NaN,81,15.0,"From first sniff to last, the nose never makes..."
203999,NaN,NaN,NaN,Chilcas,Piedra Feliz,Pinot Noir,NaN,81,15.0,"From first sniff to last, the nose never makes..."

In [44]:
clean_wine_db = merged_df.drop_duplicates()
clean_wine_db

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
233942,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233943,Portugal,Port,NaN,Casa Santa Eufemia,30-year old tawny,Port,NaN,84,NaN,Oreo eaters will enjoy the aromas of this wine...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [45]:
clean_wine_db.country.unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt', 'Albania', 'Lithuania', 'Japan', 'South Korea',
       'Montenegro', 'Tunisia', 'US-France'], dtype=object)

In [46]:
clean_wine_db = clean_wine_db[clean_wine_db['region'].notna()]
clean_wine_db

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
5,Spain,Northern Spain,Navarra,Tandem,Ars In Vitro,Tempranillo-Merlot,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,87,15.0,Blackberry and raspberry aromas show a typical...
...,...,...,...,...,...,...,...,...,...,...
233941,France,Alsace,Alsace,W. Gisselbrecht,NaN,Gewürztraminer,NaN,84,15.0,Atypically light in body and reticent on the n...
233942,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [47]:
clean_wine_db = clean_wine_db[clean_wine_db['price'].notna()]
clean_wine_db

,country,province,region,winery,vineyard,variety,title,points,price,review
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
5,Spain,Northern Spain,Navarra,Tandem,Ars In Vitro,Tempranillo-Merlot,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,87,15.0,Blackberry and raspberry aromas show a typical...
6,Italy,Sicily & Sardinia,Vittoria,Terre di Giurfo,Belsito,Frappato,Terre di Giurfo 2013 Belsito Frappato (Vittoria),87,16.0,"Here's a bright, informal red that opens with ..."
...,...,...,...,...,...,...,...,...,...,...
233941,France,Alsace,Alsace,W. Gisselbrecht,NaN,Gewürztraminer,NaN,84,15.0,Atypically light in body and reticent on the n...
233942,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [56]:
clean_wine_db.loc[clean_wine_db["title"].isna()==True]

,country,province,region,winery,vineyard,variety,title,points,price,review
151445,US,California,Napa Valley,Heitz,Martha's Vineyard,Cabernet Sauvignon,NaN,96,235.0,This tremendous 100% varietal wine hails from ...
151446,Spain,Northern Spain,Toro,Bodega Carmen Rodríguez,Carodorum Selección Especial Reserva,Tinta de Toro,NaN,96,110.0,"Ripe aromas of fig, blackberry and cassis are ..."
151447,US,California,Knights Valley,Macauley,Special Selected Late Harvest,Sauvignon Blanc,NaN,96,90.0,Mac Watson honors the memory of a wine once ma...
151448,US,Oregon,Willamette Valley,Ponzi,Reserve,Pinot Noir,NaN,96,65.0,"This spent 20 months in 30% new French oak, an..."
151449,France,Provence,Bandol,Domaine de la Bégude,La Brûlade,Provence red blend,NaN,95,66.0,"This is the top wine from La Bégude, named aft..."
...,...,...,...,...,...,...,...,...,...,...
233941,France,Alsace,Alsace,W. Gisselbrecht,NaN,Gewürztraminer,NaN,84,15.0,Atypically light in body and reticent on the n...
233942,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [48]:
clean_wine_db.loc[clean_wine_db["vineyard"].isna()==True]

,country,province,region,winery,vineyard,variety,title,points,price,review
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
7,France,Alsace,Alsace,Trimbach,NaN,Gewürztraminer,Trimbach 2012 Gewurztraminer (Alsace),87,24.0,This dry and restrained wine offers spice in p...
13,France,Alsace,Alsace,Leon Beyer,NaN,Gewürztraminer,Leon Beyer 2012 Gewurztraminer (Alsace),87,30.0,"This is a dry wine, very spicy, with a tight, ..."
15,US,California,Alexander Valley,Louis M. Martini,NaN,Cabernet Sauvignon,Louis M. Martini 2012 Cabernet Sauvignon (Alex...,87,34.0,"Slightly reduced, this wine offers a chalky, t..."
19,US,California,Central Coast,Mirassou,NaN,Chardonnay,Mirassou 2012 Chardonnay (Central Coast),87,12.0,Building on 150 years and six generations of w...
...,...,...,...,...,...,...,...,...,...,...
233940,US,New York,"The Hamptons, Long Island",Wölffer,NaN,Cabernet Franc,NaN,84,40.0,"Mushroom and tomato are coated with spicy oak,..."
233941,France,Alsace,Alsace,W. Gisselbrecht,NaN,Gewürztraminer,NaN,84,15.0,Atypically light in body and reticent on the n...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [67]:
wine_region = clean_wine_db[["country","province","region"]]
wine_region_df = wine_region.groupby(["country","province","region"]).count().reset_index()
wine_region_df = wine_region_df.reset_index()
wine_region_df["id"] = wine_region_df["index"]+1
wine_region_df = wine_region_df.drop(columns="index")
wine_region_df = wine_region_df.set_index("id")
wine_region_df

        country          province                   region
id
1     Argentina  Mendoza Province                   Agrelo
2     Argentina  Mendoza Province        Alto Valle de Uco
3     Argentina  Mendoza Province         Altos de Mendoza
4     Argentina  Mendoza Province              La Consulta
5     Argentina  Mendoza Province            Luján de Cuyo
...         ...               ...                      ...
1305         US        Washington          Snipes Mountain
1306         US        Washington            Wahluke Slope
1307         US        Washington  Walla Walla Valley (WA)
1308         US        Washington               Washington
1309         US        Washington            Yakima Valley

[1309 rows x 3 columns]

In [50]:
country= clean_wine_db["country"].sort_values().unique()

country = pd.DataFrame(country).reset_index()
country["index"] = country["index"]+1
country = country.rename(columns={0:"country"})
country

   index    country
0      1  Argentina
1      2  Australia
2      3     Canada
3      4     France
4      5      Italy
5      6      Spain
6      7         US

In [51]:
province= clean_wine_db["province"].sort_values().unique()

province = pd.DataFrame(province).reset_index()
province["index"] = province["index"]+1
province = province.rename(columns={0:"province"})
province

    index           province
0       1             Alsace
1       2          Andalucia
2       3            Arizona
3       4    Australia Other
4       5         Beaujolais
..    ...                ...
61     62            Vermont
62     63           Victoria
63     64           Virginia
64     65         Washington
65     66  Western Australia

[66 rows x 2 columns]

In [52]:
region= clean_wine_db["region"].sort_values().unique()

region = pd.DataFrame(region).reset_index()
region["index"] = region["index"]+1
region = region.rename(columns={0:"region"})
region = region.set_index("index")
region

                    region
index
1                  Abruzzo
2        Adelaida District
3                 Adelaide
4           Adelaide Hills
5          Adelaide Plains
...                    ...
1303           Yolo County
1304         York Mountain
1305   Yorkville Highlands
1306            Yountville
1307          Zonda Valley

[1307 rows x 1 columns]

In [53]:
variety= clean_wine_db["region"].sort_values().unique()

region = pd.DataFrame(region).reset_index()
region["index"] = region["index"]+1
region = region.rename(columns={0:"region"})
region

      index               region
0         2              Abruzzo
1         3    Adelaida District
2         4             Adelaide
3         5       Adelaide Hills
4         6      Adelaide Plains
...     ...                  ...
1302   1304          Yolo County
1303   1305        York Mountain
1304   1306  Yorkville Highlands
1305   1307           Yountville
1306   1308         Zonda Valley

[1307 rows x 2 columns]

In [54]:
# Change values to id's to insert in the db
clean_wine_db_df = clean_wine_db.merge(country, how="inner", left_on="country", right_on="country").rename(columns={"index": "country_id"}).drop(columns="country")
clean_wine_db_df = clean_wine_db_df.merge(region, how="inner", left_on="region", right_on="region").rename(columns={"index": "region_id"}).drop(columns="region")
clean_wine_db_df = clean_wine_db_df.merge(province, how="inner", left_on="province", right_on="province").rename(columns={"index": "province_id"}).drop(columns="province")
clean_wine_db_df

,winery,vineyard,variety,title,points,price,review,country_id,region_id,province_id
0,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and...",7,1295,44
1,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this...",7,1295,44
2,Hawkins Cellars,NaN,Pinot Noir,Hawkins Cellars 2009 Pinot Noir (Willamette Va...,86,22.0,"A stiff, tannic wine, this slowly opens and br...",7,1295,44
3,Le Cadeau,NaN,Pinot Noir,Le Cadeau 2014 Pinot Noir (Willamette Valley),91,38.0,This wine is bursting with gorgeous cherry fru...,7,1295,44
4,Silvan Ridge,Reserve,Pinot Noir,Silvan Ridge 2006 Reserve Pinot Noir (Willamet...,85,28.0,"There is an odd, piercing edge to the aromas, ...",7,1295,44
...,...,...,...,...,...,...,...,...,...,...
131267,Calliope,NaN,Sauvignon Blanc,Calliope 2013 Sauvignon Blanc (British Columbia),88,20.0,"Fresh and lively, this works the green side of...",3,148,7
131268,Vanessa,NaN,Meritage,Vanessa 2012 Meritage (Similkameen Valley),92,32.0,"West of the Okanagan valley, Similkameen Valle...",3,1048,7
131269,Vanessa,NaN,Syrah,Vanessa 2012 Syrah (Similkameen Valley),93,34.0,For those who want a little funk in their Syra...,3,1048,7
131270,Domaine Pinnacle,Ice Apple Wine,Apple,Domaine Pinnacle NV Ice Apple Wine Apple (Canada),89,33.0,With over 80 apples used to produce each bottl...,3,178,10
131271,La Face Cachée de la Pomme,Neige Apple Ice Wine,Apple,NaN,90,35.0,"A beautiful Quebec classic ice cider, with vib...",3,906,10

In [57]:
# insert into database
from sqlalchemy import create_engine
engine = create_engine('postgresql://postgres:karen@localhost:5432/wines')
country.to_sql('country', engine)
region.to_sql('region', engine)
province.to_sql('province', engine)
clean_wine_db_df.to_sql('wines', engine)

OperationalError: (psycopg2.OperationalError)
(Background on this error at: http://sqlalche.me/e/13/e3q8)

In [59]:
# Connect to local database

rds_connection_string = "postgres:karen@localhost:5432/wines"
engine = create_engine(f'postgresql://{rds_connection_string}')

### Check for tables
# engine.table_names()

### Use pandas to load csv converted DataFrame into database

country.to_sql(name='country', con=engine, if_exists='append', index=False)

### Use pandas to load json converted DataFrame into database

# new_customer_location_df.to_sql(name='customer_location', con=engine, if_exists='append', index=False)

### Confirm data has been added by querying the customer_name table
# * NOTE: can also check using pgAdmin

pd.read_sql_query('select * from country', con=engine).head()

# ## Confirm data has been added by querying the customer_location table

# pd.read_sql_query('select * from customer_location', con=engine).head()

OperationalError: (psycopg2.OperationalError)
(Background on this error at: http://sqlalche.me/e/13/e3q8)