In [3]:
import pandas as pd
from sqlalchemy import create_engine

Store CSV into DataFrame

In [4]:
csv_file1 = "../Resources/winemag-data130.csv"
csv_file2 = "../Resources/winemag-data150.csv"
wine_data_data130_df = pd.read_csv(csv_file1, encoding="UTF-8")
wine_data_data150_df = pd.read_csv(csv_file2)
wine_data_data130_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [5]:
wine_data_data150_df["variety"].unique

<bound method Series.unique of 0         Cabernet Sauvignon
1              Tinta de Toro
2            Sauvignon Blanc
3                 Pinot Noir
4         Provence red blend
                 ...
150925           White Blend
150926       Champagne Blend
150927           White Blend
150928       Champagne Blend
150929          Pinot Grigio
Name: variety, Length: 150930, dtype: object>

In [6]:
wine_data_data130_df.loc[wine_data_data130_df["variety"]=="Heitz has made this stellar rosÃ© from the rare Grignolino grape since 1961. Ruby grapefruit-red, it's sultry with strawberry, watermelon, orange zest and salty spice flavor, highlighted with vibrant floral aromas.",:]

Empty DataFrame
Columns: [Unnamed: 0, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

In [7]:
# Create a filtered dataframe from specific columns
premises_cols= ["country","province","region_1","winery","designation","variety","title","points","price","description",]
wine_130_ts= wine_data_data130_df[premises_cols].copy()

# Rename the column headers
wine_130_ts=wine_130_ts.rename(columns={"description":"review",
                                        "designation":"vineyard",
                                        "region_1":"region"
                                       })


wine_130_ts

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Mosel,NaN,Dr. H. Thanisch (Erben Müller-Burggraef),Brauneberger Juffer-Sonnenuhr Spätlese,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,90,28.0,Notes of honeysuckle and cantaloupe sweeten th...
129967,US,Oregon,Oregon,Citation,NaN,Pinot Noir,Citation 2004 Pinot Noir (Oregon),90,75.0,Citation is given as much as a decade of bottl...
129968,France,Alsace,Alsace,Domaine Gresser,Kritt,Gewürztraminer,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,90,30.0,Well-drained gravel soil gives this wine its c...
129969,France,Alsace,Alsace,Domaine Marcel Deiss,NaN,Pinot Gris,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),90,32.0,"A dry style of Pinot Gris, this is crisp with ..."
129970,France,Alsace,Alsace,Domaine Schoffit,Lieu-dit Harth Cuvée Caroline,Gewürztraminer,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,90,21.0,"Big, rich and off-dry, this is powered by inte..."

In [8]:
# Create a filtered dataframe from specific columns
premises_cols2= ["country","province","region_1","winery","designation","variety","points","price","description"]
wine_150_ts= wine_data_data150_df[premises_cols2].copy()

# Rename the column headers
wine_150_ts=wine_150_ts.rename(columns={"description":"review",
                                        "designation":"vineyard",
                                        "region_1":"region"
                                       })

wine_150_ts

,country,province,region,winery,vineyard,variety,points,price,review
0,US,California,Napa Valley,Heitz,Martha's Vineyard,Cabernet Sauvignon,96,235.0,This tremendous 100% varietal wine hails from ...
1,Spain,Northern Spain,Toro,Bodega Carmen Rodríguez,Carodorum Selección Especial Reserva,Tinta de Toro,96,110.0,"Ripe aromas of fig, blackberry and cassis are ..."
2,US,California,Knights Valley,Macauley,Special Selected Late Harvest,Sauvignon Blanc,96,90.0,Mac Watson honors the memory of a wine once ma...
3,US,Oregon,Willamette Valley,Ponzi,Reserve,Pinot Noir,96,65.0,"This spent 20 months in 30% new French oak, an..."
4,France,Provence,Bandol,Domaine de la Bégude,La Brûlade,Provence red blend,95,66.0,"This is the top wine from La Bégude, named aft..."
...,...,...,...,...,...,...,...,...,...
150925,Italy,Southern Italy,Fiano di Avellino,Feudi di San Gregorio,NaN,White Blend,91,20.0,Many people feel Fiano represents southern Ita...
150926,France,Champagne,Champagne,H.Germain,Cuvée Prestige,Champagne Blend,91,27.0,"Offers an intriguing nose with ginger, lime an..."
150927,Italy,Southern Italy,Fiano di Avellino,Terredora,Terre di Dora,White Blend,91,20.0,This classic example comes from a cru vineyard...
150928,France,Champagne,Champagne,Gosset,Grand Brut Rosé,Champagne Blend,90,52.0,"A perfect salmon shade, with scents of peaches..."
150929,Italy,Northeastern Italy,Alto Adige,Alois Lageder,NaN,Pinot Grigio,90,15.0,More Pinot Grigios should taste like this. A r...

In [9]:
merged_df=wine_130_ts.merge(wine_150_ts, how="outer")

pd.set_option('display.max_columns', None)
merged_df

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
233942,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233943,Portugal,Port,NaN,Casa Santa Eufemia,30-year old tawny,Port,NaN,84,NaN,Oreo eaters will enjoy the aromas of this wine...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [10]:
duplicates = merged_df.loc[merged_df.duplicated(['review','country'])].sort_values('country')
duplicates

,country,province,region,winery,vineyard,variety,title,points,price,review
152515,Albania,Mirditë,NaN,Arbëri,NaN,Kallmet,NaN,88,20.0,This garnet-colored wine made from 100% Kallme...
233814,Argentina,Mendoza Province,Uco Valley,Cabra Montes,NaN,Chardonnay,NaN,86,9.0,"Fresh, tropical, and welcoming. Sweet and lush..."
165169,Argentina,Mendoza Province,Mendoza,Nieto Senetiner,Reserva,Torrontés,NaN,80,11.0,"Shows barely any color and then a hard, vapid,..."
165170,Argentina,Mendoza Province,Mendoza,Nieto Senetiner,Reserva,Torrontés,NaN,80,11.0,"Shows barely any color and then a hard, vapid,..."
165178,Argentina,Mendoza Province,Mendoza,Viniterra,Serie Terra Spakling,Malbec,NaN,80,14.0,Red in color and flat in terms of bubbles and ...
...,...,...,...,...,...,...,...,...,...,...
46273,NaN,NaN,NaN,Orbelus,Hrumki Melnik 55 Mourvèdre Marselan,Red Blend,Orbelus 2012 Hrumki Melnik 55 Mourvèdre Marsel...,89,25.0,An interesting blend of indigenous Bulgarian a...
83277,NaN,NaN,NaN,Gotsa Family Wines,Dry Unfiltered Rkatsiteli Mtsvane,White Blend,Gotsa Family Wines 2015 Dry Unfiltered Rkatsit...,88,25.0,"Amber to the eye, this wine features an entici..."
126113,NaN,NaN,NaN,Neumeister,Steirische Klassik,Gelber Muskateller,Neumeister 2016 Steirische Klassik Gelber Musk...,92,21.0,"A lively whiff of white blossom, Muscat grapes..."
203998,NaN,NaN,NaN,Chilcas,Piedra Feliz,Pinot Noir,NaN,81,15.0,"From first sniff to last, the nose never makes..."
203999,NaN,NaN,NaN,Chilcas,Piedra Feliz,Pinot Noir,NaN,81,15.0,"From first sniff to last, the nose never makes..."

In [11]:
clean_wine_db = merged_df.drop_duplicates()
clean_wine_db

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
233942,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233943,Portugal,Port,NaN,Casa Santa Eufemia,30-year old tawny,Port,NaN,84,NaN,Oreo eaters will enjoy the aromas of this wine...
233944,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233945,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233946,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [14]:
len(clean_wine_db["country"].unique())

51

In [18]:
len(clean_wine_db["title"].unique())

118841

In [21]:
variery_points_df=clean_wine_db[["variety", "points"]]
variery_points_df

                variety  points
0           White Blend      87
1        Portuguese Red      87
2            Pinot Gris      87
3              Riesling      87
4            Pinot Noir      87
...                 ...     ...
233942   Syrah-Grenache      84
233943             Port      84
233944           Merlot      84
233945  Sauvignon Blanc      84
233946       Chardonnay      84

[169793 rows x 2 columns]

In [30]:
title_points_df=clean_wine_db[["title", "points"]]
title_points_df=title_points_df[title_points_df["title"].notna()]
title_points_df

                                                    title  points
0                       Nicosia 2013 Vulkà Bianco  (Etna)      87
1           Quinta dos Avidagos 2011 Avidagos Red (Douro)      87
2           Rainstorm 2013 Pinot Gris (Willamette Valley)      87
3       St. Julian 2013 Reserve Late Harvest Riesling ...      87
4       Sweet Cheeks 2012 Vintner's Reserve Wild Child...      87
...                                                   ...     ...
151440  Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...      90
151441                  Citation 2004 Pinot Noir (Oregon)      90
151442  Domaine Gresser 2013 Kritt Gewurztraminer (Als...      90
151443      Domaine Marcel Deiss 2012 Pinot Gris (Alsace)      90
151444  Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...      90

[119988 rows x 2 columns]

In [32]:
len(title_points_df["title"].unique())

118840

In [33]:
title_points_df.value_counts()

title                                                               points
Korbel NV Sweet Rosé Sparkling (California)                         86        5
Segura Viudas NV Extra Dry Sparkling (Cava)                         86        4
Ferrari NV Rosé Sparkling (Trento)                                  90        4
J Vineyards & Winery NV Brut Rosé Sparkling (Russian River Valley)  87        4
Bailly-Lapierre NV Brut  (Crémant de Bourgogne)                     90        4
                                                                             ..
Nelle 2014 Syrah (California)                                       92        1
Nelles 2009 1479N Ruber Spätburgunder (Ahr)                         86        1
Nelms Road 2007 Merlot (Washington)                                 89        1
Nelms Road 2012 Cabernet Sauvignon (Washington)                     87        1
1+1=3 2008 Rosé Cabernet Sauvignon (Penedès)                        82        1
Length: 119682, dtype: int64

In [34]:
title_points_df.groupby("title").mean()

                                                    points
title
1+1=3 2008 Rosé Cabernet Sauvignon (Penedès)          82.0
1+1=3 NV Brut Sparkling (Cava)                        87.0
1+1=3 NV Cygnus Brut Nature Reserva Made With O...    89.0
1+1=3 NV Rosé Sparkling (Cava)                        86.0
10 Knots 2006 Beachcomber White (Paso Robles)         83.0
...                                                    ...
àMaurice 2014 Fred Estate Syrah (Walla Walla Va...    88.0
àMaurice NV Pour Me Red (Columbia Valley (WA))        89.0
Štoka 2009 Izbrani Teran (Kras)                       88.0
Štoka 2011 Grganja Vitovska (Kras)                    90.0
Štoka 2011 Izbrani Teran (Kras)                       90.0

[118840 rows x 1 columns]

In [26]:
variery_points_df.loc[variery_points_df["variety"]=="Moscatel Roxo"]

              variety  points
19692   Moscatel Roxo      86
52806   Moscatel Roxo      94
83141   Moscatel Roxo      88
105770  Moscatel Roxo      91
135980  Moscatel Roxo      86
146277  Moscatel Roxo      92
209803  Moscatel Roxo      85

In [24]:
variery_points_df.value_counts()

variety                 points
Chardonnay              87        1971
Pinot Noir              90        1944
                        88        1780
                        87        1776
Chardonnay              88        1765
                                  ...
Moscatel de Alejandría  83           1
Moscatel Roxo           94           1
                        92           1
                        91           1
Abouriou                85           1
Length: 4599, dtype: int64

In [23]:
variery_points_df.groupby("variety").mean()

                points
variety
Abouriou     87.666667
Agiorgitiko  86.292929
Aglianico    89.100000
Aidani       82.000000
Airen        81.666667
...                ...
Zinfandel    87.317502
Zlahtina     86.666667
Zweigelt     87.950820
Çalkarası    86.500000
Žilavka      87.000000

[756 rows x 1 columns]