In [1]:
import pandas as pd
from sqlalchemy import create_engine

Store CSV into DataFrame

In [2]:
csv_file1 = "../Resources/winemag-data130.csv"
csv_file2 = "../Resources/winemag-data150.csv"
wine_data_data130_df = pd.read_csv(csv_file1, encoding="UTF-8")
wine_data_data150_df = pd.read_csv(csv_file2)
wine_data_data130_df.head()

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [3]:
wine_data_data150_df["variety"].unique

<bound method Series.unique of 0         Cabernet Sauvignon
1              Tinta de Toro
2            Sauvignon Blanc
3                 Pinot Noir
4         Provence red blend
                 ...
150925           White Blend
150926       Champagne Blend
150927           White Blend
150928       Champagne Blend
150929          Pinot Grigio
Name: variety, Length: 150930, dtype: object>

In [4]:
wine_data_data130_df.loc[wine_data_data130_df["variety"]=="Heitz has made this stellar rosÃ© from the rare Grignolino grape since 1961. Ruby grapefruit-red, it's sultry with strawberry, watermelon, orange zest and salty spice flavor, highlighted with vibrant floral aromas.",:]

Empty DataFrame
Columns: [Unnamed: 0, country, description, designation, points, price, province, region_1, region_2, taster_name, taster_twitter_handle, title, variety, winery]
Index: []

In [5]:
# Create a filtered dataframe from specific columns
premises_cols= ["country","province","region_1","winery","designation","variety","title","points","price","description",]
wine_130_ts= wine_data_data130_df[premises_cols].copy()

# Rename the column headers
wine_130_ts=wine_130_ts.rename(columns={"description":"review",
                                        "designation":"vineyard",
                                        "region_1":"region"
                                       })


wine_130_ts

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
129966,Germany,Mosel,NaN,Dr. H. Thanisch (Erben Müller-Burggraef),Brauneberger Juffer-Sonnenuhr Spätlese,Riesling,Dr. H. Thanisch (Erben Müller-Burggraef) 2013 ...,90,28.0,Notes of honeysuckle and cantaloupe sweeten th...
129967,US,Oregon,Oregon,Citation,NaN,Pinot Noir,Citation 2004 Pinot Noir (Oregon),90,75.0,Citation is given as much as a decade of bottl...
129968,France,Alsace,Alsace,Domaine Gresser,Kritt,Gewürztraminer,Domaine Gresser 2013 Kritt Gewurztraminer (Als...,90,30.0,Well-drained gravel soil gives this wine its c...
129969,France,Alsace,Alsace,Domaine Marcel Deiss,NaN,Pinot Gris,Domaine Marcel Deiss 2012 Pinot Gris (Alsace),90,32.0,"A dry style of Pinot Gris, this is crisp with ..."
129970,France,Alsace,Alsace,Domaine Schoffit,Lieu-dit Harth Cuvée Caroline,Gewürztraminer,Domaine Schoffit 2012 Lieu-dit Harth Cuvée Car...,90,21.0,"Big, rich and off-dry, this is powered by inte..."

In [6]:
# Create a filtered dataframe from specific columns
premises_cols2= ["country","province","region_1","winery","designation","variety","points","price","description"]
wine_150_ts= wine_data_data150_df[premises_cols2].copy()

# Rename the column headers
wine_150_ts=wine_150_ts.rename(columns={"description":"review",
                                        "designation":"vineyard",
                                        "region_1":"region"
                                       })

wine_150_ts

,country,province,region,winery,vineyard,variety,points,price,review
0,US,California,Napa Valley,Heitz,Martha's Vineyard,Cabernet Sauvignon,96,235.0,This tremendous 100% varietal wine hails from ...
1,Spain,Northern Spain,Toro,Bodega Carmen Rodríguez,Carodorum Selección Especial Reserva,Tinta de Toro,96,110.0,"Ripe aromas of fig, blackberry and cassis are ..."
2,US,California,Knights Valley,Macauley,Special Selected Late Harvest,Sauvignon Blanc,96,90.0,Mac Watson honors the memory of a wine once ma...
3,US,Oregon,Willamette Valley,Ponzi,Reserve,Pinot Noir,96,65.0,"This spent 20 months in 30% new French oak, an..."
4,France,Provence,Bandol,Domaine de la Bégude,La Brûlade,Provence red blend,95,66.0,"This is the top wine from La Bégude, named aft..."
...,...,...,...,...,...,...,...,...,...
150925,Italy,Southern Italy,Fiano di Avellino,Feudi di San Gregorio,NaN,White Blend,91,20.0,Many people feel Fiano represents southern Ita...
150926,France,Champagne,Champagne,H.Germain,Cuvée Prestige,Champagne Blend,91,27.0,"Offers an intriguing nose with ginger, lime an..."
150927,Italy,Southern Italy,Fiano di Avellino,Terredora,Terre di Dora,White Blend,91,20.0,This classic example comes from a cru vineyard...
150928,France,Champagne,Champagne,Gosset,Grand Brut Rosé,Champagne Blend,90,52.0,"A perfect salmon shade, with scents of peaches..."
150929,Italy,Northeastern Italy,Alto Adige,Alois Lageder,NaN,Pinot Grigio,90,15.0,More Pinot Grigios should taste like this. A r...

In [7]:
#merged tables
merged_df=wine_130_ts.merge(wine_150_ts, how="outer")

pd.set_option('display.max_columns', None)
merged_df

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
233944,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233945,Portugal,Port,NaN,Casa Santa Eufemia,30-year old tawny,Port,NaN,84,NaN,Oreo eaters will enjoy the aromas of this wine...
233946,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233947,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233948,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [8]:
#Looking for duplicates
duplicates = merged_df.loc[merged_df.duplicated(['review','country'])].sort_values('country')
duplicates

,country,province,region,winery,vineyard,variety,title,points,price,review
152515,Albania,Mirditë,NaN,Arbëri,NaN,Kallmet,NaN,88,20.0,This garnet-colored wine made from 100% Kallme...
233816,Argentina,Mendoza Province,Uco Valley,Cabra Montes,NaN,Chardonnay,NaN,86,9.0,"Fresh, tropical, and welcoming. Sweet and lush..."
165169,Argentina,Mendoza Province,Mendoza,Nieto Senetiner,Reserva,Torrontés,NaN,80,11.0,"Shows barely any color and then a hard, vapid,..."
165170,Argentina,Mendoza Province,Mendoza,Nieto Senetiner,Reserva,Torrontés,NaN,80,11.0,"Shows barely any color and then a hard, vapid,..."
165178,Argentina,Mendoza Province,Mendoza,Viniterra,Serie Terra Spakling,Malbec,NaN,80,14.0,Red in color and flat in terms of bubbles and ...
...,...,...,...,...,...,...,...,...,...,...
46273,NaN,NaN,NaN,Orbelus,Hrumki Melnik 55 Mourvèdre Marselan,Red Blend,Orbelus 2012 Hrumki Melnik 55 Mourvèdre Marsel...,89,25.0,An interesting blend of indigenous Bulgarian a...
83277,NaN,NaN,NaN,Gotsa Family Wines,Dry Unfiltered Rkatsiteli Mtsvane,White Blend,Gotsa Family Wines 2015 Dry Unfiltered Rkatsit...,88,25.0,"Amber to the eye, this wine features an entici..."
126113,NaN,NaN,NaN,Neumeister,Steirische Klassik,Gelber Muskateller,Neumeister 2016 Steirische Klassik Gelber Musk...,92,21.0,"A lively whiff of white blossom, Muscat grapes..."
203998,NaN,NaN,NaN,Chilcas,Piedra Feliz,Pinot Noir,NaN,81,15.0,"From first sniff to last, the nose never makes..."
203999,NaN,NaN,NaN,Chilcas,Piedra Feliz,Pinot Noir,NaN,81,15.0,"From first sniff to last, the nose never makes..."

In [9]:
#Droping Duplicates
clean_wine_db = merged_df.drop_duplicates()
clean_wine_db

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
1,Portugal,Douro,NaN,Quinta dos Avidagos,Avidagos,Portuguese Red,Quinta dos Avidagos 2011 Avidagos Red (Douro),87,15.0,"This is ripe and fruity, a wine that is smooth..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
...,...,...,...,...,...,...,...,...,...,...
233944,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233945,Portugal,Port,NaN,Casa Santa Eufemia,30-year old tawny,Port,NaN,84,NaN,Oreo eaters will enjoy the aromas of this wine...
233946,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233947,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233948,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [10]:
clean_wine_db.country.unique()

array(['Italy', 'Portugal', 'US', 'Spain', 'France', 'Germany',
       'Argentina', 'Chile', 'Australia', 'Austria', 'South Africa',
       'New Zealand', 'Israel', 'Hungary', 'Greece', 'Romania', 'Mexico',
       'Canada', nan, 'Turkey', 'Czech Republic', 'Slovenia',
       'Luxembourg', 'Croatia', 'Georgia', 'Uruguay', 'England',
       'Lebanon', 'Serbia', 'Brazil', 'Moldova', 'Morocco', 'Peru',
       'India', 'Bulgaria', 'Cyprus', 'Armenia', 'Switzerland',
       'Bosnia and Herzegovina', 'Ukraine', 'Slovakia', 'Macedonia',
       'China', 'Egypt', 'Albania', 'Lithuania', 'Japan', 'South Korea',
       'Montenegro', 'Tunisia', 'US-France'], dtype=object)

In [11]:
#taking NA from region
clean_wine_db = clean_wine_db[clean_wine_db['region'].notna()]
clean_wine_db

,country,province,region,winery,vineyard,variety,title,points,price,review
0,Italy,Sicily & Sardinia,Etna,Nicosia,Vulkà Bianco,White Blend,Nicosia 2013 Vulkà Bianco (Etna),87,NaN,"Aromas include tropical fruit, broom, brimston..."
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
5,Spain,Northern Spain,Navarra,Tandem,Ars In Vitro,Tempranillo-Merlot,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,87,15.0,Blackberry and raspberry aromas show a typical...
...,...,...,...,...,...,...,...,...,...,...
233943,France,Alsace,Alsace,W. Gisselbrecht,NaN,Gewürztraminer,NaN,84,15.0,Atypically light in body and reticent on the n...
233944,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233946,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233947,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233948,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

In [12]:
#taking NA from price
clean_wine_db = clean_wine_db[clean_wine_db['price'].notna()]
clean_wine_db

,country,province,region,winery,vineyard,variety,title,points,price,review
2,US,Oregon,Willamette Valley,Rainstorm,NaN,Pinot Gris,Rainstorm 2013 Pinot Gris (Willamette Valley),87,14.0,"Tart and snappy, the flavors of lime flesh and..."
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
5,Spain,Northern Spain,Navarra,Tandem,Ars In Vitro,Tempranillo-Merlot,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,87,15.0,Blackberry and raspberry aromas show a typical...
6,Italy,Sicily & Sardinia,Vittoria,Terre di Giurfo,Belsito,Frappato,Terre di Giurfo 2013 Belsito Frappato (Vittoria),87,16.0,"Here's a bright, informal red that opens with ..."
...,...,...,...,...,...,...,...,...,...,...
233943,France,Alsace,Alsace,W. Gisselbrecht,NaN,Gewürztraminer,NaN,84,15.0,Atypically light in body and reticent on the n...
233944,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...
233946,US,California,California,Delicato,NaN,Merlot,NaN,84,6.0,"Outside of the vineyard, wines like this are w..."
233947,Argentina,Mendoza Province,Uco Valley,Finca El Portillo,NaN,Sauvignon Blanc,NaN,84,9.0,"Heavy and basic, with melon and pineapple arom..."
233948,Australia,Australia Other,South Eastern Australia,Jacob's Creek,NaN,Chardonnay,NaN,84,8.0,"Smooth in the mouth, this Chard starts off wit..."

### GENERAL TABLE WITHOUT NORMALIZATION

In [13]:
#taking NA from vineyard
clean_wine_db = clean_wine_db[clean_wine_db['vineyard'].notna()]
clean_wine_db1=clean_wine_db
clean_wine_db1

,country,province,region,winery,vineyard,variety,title,points,price,review
3,US,Michigan,Lake Michigan Shore,St. Julian,Reserve Late Harvest,Riesling,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ..."
4,US,Oregon,Willamette Valley,Sweet Cheeks,Vintner's Reserve Wild Child Block,Pinot Noir,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,87,65.0,"Much like the regular bottling from 2012, this..."
5,Spain,Northern Spain,Navarra,Tandem,Ars In Vitro,Tempranillo-Merlot,Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...,87,15.0,Blackberry and raspberry aromas show a typical...
6,Italy,Sicily & Sardinia,Vittoria,Terre di Giurfo,Belsito,Frappato,Terre di Giurfo 2013 Belsito Frappato (Vittoria),87,16.0,"Here's a bright, informal red that opens with ..."
9,France,Alsace,Alsace,Jean-Baptiste Adam,Les Natures,Pinot Gris,Jean-Baptiste Adam 2012 Les Natures Pinot Gris...,87,27.0,This has great depth of flavor with its fresh ...
...,...,...,...,...,...,...,...,...,...,...
233932,Argentina,Mendoza Province,Tupungato,Domaine Jean Bousquet,Organic,Malbec,NaN,84,13.0,"Dark and dense, with extracted black cherry, l..."
233936,France,Alsace,Alsace,Marc Kreydenweiss,Andlau,Riesling,NaN,84,21.0,Opens with spice aromas that seem a bit unusua...
233938,US,New York,North Fork of Long Island,Martha Clara,Five-O,Red Blend,NaN,84,25.0,"Half Merlot, with the rest Cabernet Sauvignon,..."
233939,US,California,Napa Valley,Pine Ridge,Crimson Creek,Merlot,NaN,84,27.0,Tastes kind of soft and thick in jammy cherry ...
233944,US,California,Santa Barbara County,Casa Barranca,Bungalow Red,Syrah-Grenache,NaN,84,15.0,A Syrah-Grenache blend that's dry and rustical...

# 1st Table: COUNTRY

In [14]:
#Country Catalogue
country= clean_wine_db["country"].sort_values().unique()

country = pd.DataFrame(country).reset_index()
country["index"] = country["index"]+1
country = country.rename(columns={0:"country"})
#country=country.set_index("index")
country

   index    country
0      1  Argentina
1      2  Australia
2      3     Canada
3      4     France
4      5      Italy
5      6      Spain
6      7         US

# 2nd Table: PROVINCE

In [15]:
#Province Catalogue
province= clean_wine_db["province"].sort_values().unique()

province = pd.DataFrame(province).reset_index()
province["index"] = province["index"]+1
province = province.rename(columns={0:"province"})
#province=province.set_index("index")
province

    index           province
0       1             Alsace
1       2          Andalucia
2       3            Arizona
3       4    Australia Other
4       5         Beaujolais
..    ...                ...
60     61            Vermont
61     62           Victoria
62     63           Virginia
63     64         Washington
64     65  Western Australia

[65 rows x 2 columns]

In [16]:
province.loc[province["province"]=="Mendoza Province"]

    index          province
29     30  Mendoza Province

# 3rd Table: REGION

In [17]:
# 1st Table: COUNTRY#Region Catalogue
region= clean_wine_db["region"].sort_values().unique()

region = pd.DataFrame(region).reset_index()
region["index"] = region["index"]+1
region = region.rename(columns={0:"region"})
#region=region.set_index("index")
region.head()

   index                     region
0      1                    Abruzzo
1      2          Adelaida District
2      3                   Adelaide
3      4             Adelaide Hills
4      5  Aglianico del Beneventano

# 4th Table: WINERY

In [18]:
# 1st Table: COUNTRY#Winery Catalogue
winery= clean_wine_db["winery"].sort_values().unique()

winery = pd.DataFrame(winery).reset_index()
winery["index"] = winery["index"]+1
winery = winery.rename(columns={0:"winery"})
#winery=winery.set_index("index")
winery.head()

   index            winery
0      1             1+1=3
1      2          10 Knots
2      3  100 Percent Wine
3      4      1000 Stories
4      5        12 Linajes

# 5th Table: VARIETY

In [19]:
# 1st Table: COUNTRY#Variety Catalogue
variety= clean_wine_db["variety"].sort_values().unique()

variety = pd.DataFrame(variety).reset_index()
variety["index"] = variety["index"]+1
variety= variety.rename(columns={0:"variety"})
#variety=variety.set_index("index")
variety.head()

   index    variety
0      1   Abouriou
1      2  Aglianico
2      3      Airen
3      4     Albana
4      5  Albanello

# 6th Table: VINEYARD

In [20]:
# 1st Table: COUNTRY#Vineyard Catalogue
vineyard= clean_wine_db["vineyard"].sort_values().unique()

vineyard = pd.DataFrame(vineyard).reset_index()
vineyard["index"] = vineyard["index"]+1
vineyard= vineyard.rename(columns={0:"vineyard"})
#vineyard=vineyard.set_index("index")
vineyard.head()

   index                           vineyard
0      1                                "M"
1      2  #19 Phantom Limb Belmont Vineyard
2      3                       #50 Mon Chou
3      4                      #SocialSecret
4      5                              %@#$!

# 7th Table: NORMALIZED DATA

In [21]:
# 1st Table: COUNTRY# Change values to id's to insert in the db
clean_wine_db_df = clean_wine_db.merge(country, how="inner", left_on="country", right_on="country").rename(columns={"index": "country_id"}).drop(columns="country")
clean_wine_db_df = clean_wine_db_df.merge(region, how="inner", left_on="region", right_on="region").rename(columns={"index": "region_id"}).drop(columns="region")
clean_wine_db_df = clean_wine_db_df.merge(province, how="inner", left_on="province", right_on="province").rename(columns={"index": "province_id"}).drop(columns="province")
clean_wine_db_df = clean_wine_db_df.merge(winery, how="inner", left_on="winery", right_on="winery").rename(columns={"index": "winery_id"}).drop(columns="winery")
clean_wine_db_df = clean_wine_db_df.merge(variety, how="inner", left_on="variety", right_on="variety").rename(columns={"index": "variety_id"}).drop(columns="variety")
clean_wine_db_df = clean_wine_db_df.merge(vineyard, how="inner", left_on="vineyard", right_on="vineyard").rename(columns={"index": "vineyard_id"}).drop(columns="vineyard")

# Ordering Columns
premises_cols=["country_id","region_id","province_id","winery_id","variety_id","vineyard_id","title",
              "points","price","review"]
clean_wine_db_df= clean_wine_db_df[premises_cols].copy().reset_index()
clean_wine_db_df["id"] = clean_wine_db_df["index"]+1
clean_wine_db_df = clean_wine_db_df.drop(columns="index")
clean_wine_db_df= clean_wine_db_df.rename(columns={"id":"index"})
# clean_wine_db_df = clean_wine_db_df.set_index("index")
clean_wine_db_df.head()

,country_id,region_id,province_id,winery_id,variety_id,vineyard_id,title,points,price,review,index
0,7,529,31,9759,348,26729,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ...",1
1,7,387,9,5227,348,26729,Geyser Peak 1998 Reserve Late Harvest Riesling...,86,19.0,"Even before you smell it, you can tell this is...",2
2,7,276,64,3302,348,26729,Covey Run 2008 Reserve Late Harvest Riesling (...,85,12.0,Despite the reserve and late harvest designati...,3
3,7,716,9,8665,87,26729,NaN,87,36.0,"Very sweet, with honey-rich apricot, tangerine...",4
4,7,488,64,7,488,26729,14 Hands 2015 Reserve Late Harvest Viognier (H...,88,22.0,The aromas are somewhat light considering the ...,5

In [22]:
clean_wine_db_df = clean_wine_db_df.reset_index()
clean_wine_db_df.head()

,level_0,country_id,region_id,province_id,winery_id,variety_id,vineyard_id,title,points,price,review,index
0,0,7,529,31,9759,348,26729,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ...",1
1,1,7,387,9,5227,348,26729,Geyser Peak 1998 Reserve Late Harvest Riesling...,86,19.0,"Even before you smell it, you can tell this is...",2
2,2,7,276,64,3302,348,26729,Covey Run 2008 Reserve Late Harvest Riesling (...,85,12.0,Despite the reserve and late harvest designati...,3
3,3,7,716,9,8665,87,26729,NaN,87,36.0,"Very sweet, with honey-rich apricot, tangerine...",4
4,4,7,488,64,7,488,26729,14 Hands 2015 Reserve Late Harvest Viognier (H...,88,22.0,The aromas are somewhat light considering the ...,5

In [23]:
clean_wine_db_df[pd.DataFrame.isnull(clean_wine_db_df["index"])]

TypeError: super(type, obj): obj must be an instance or subtype of type

# Conecting to database

In [24]:
### normalized_wine_region_df insert into database

from sqlalchemy import create_engine

connection_string="postgres:karen@localhost:5432/wines"
engine = create_engine(f'postgresql://{connection_string}')

# Confirm tables
engine.table_names()

ModuleNotFoundError: No module named 'psycopg2'

In [ ]:
### Use pandas to load csv converted DataFrame into database

# country.to_sql(name='country', con=engine, if_exists='append', index=False)
# # clean_wine_db_df.to_sql(name='clean_wine_db_df', con=engine, if_exists='append', index=False)
# region.to_sql(name='region', con=engine, if_exists='append', index=False)
# province.to_sql(name='province', con=engine, if_exists='append', index=False)
# winery.to_sql(name='winery', con=engine, if_exists='append', index=False)
# variety.to_sql(name='variety', con=engine, if_exists='append', index=False)
# vineyard.to_sql(name='vineyard', con=engine, if_exists='append', index=False)

In [ ]:
##TIENE ERROR

### Use pandas to load csv converted DataFrame into database

# clean_wine_db_df.to_sql(name='clean_wine_db_df', con=engine, if_exists='append', index=False)

In [ ]:
### Confirm data has been added by querying the each table
## NOTE: can also check using pgAdmin

pd.read_sql_query('select * from country', con=engine).head()

### Confirm data has been added by querying the customer_location table

# pd.read_sql_query('select * from customer_location', con=engine).head()

# Creation process of an Ultra NORMALIZED Table

## CONJUNCTION Table

In [25]:
wine_region = clean_wine_db1[["country","province","region"]]
wine_region_df = wine_region.groupby(["country","province","region"]).count().reset_index()
wine_region_df = wine_region_df.reset_index()
wine_region_df["id"] = wine_region_df["index"]+1# 1st Table: COUNTRY
wine_region_df = wine_region_df.drop(columns="index")
wine_region_df = wine_region_df.set_index("id")
wine_region_df.head()

      country          province             region
id
1   Argentina  Mendoza Province             Agrelo
2   Argentina  Mendoza Province  Alto Valle de Uco
3   Argentina  Mendoza Province        La Consulta
4   Argentina  Mendoza Province      Luján de Cuyo
5   Argentina  Mendoza Province              Maipú

# 8th Table: Normalized CONJUNCTION Table

In [26]:
# 1st Table: COUNTRY# Change values to id's to insert in the db

normalized_wine_region_df = wine_region_df.merge(country, how="inner", left_on="country", right_on="country").rename(columns={"index": "country_id"}).drop(columns="country")
normalized_wine_region_df = normalized_wine_region_df.merge(province, how="inner", left_on="province", right_on="province").rename(columns={"index": "province_id"}).drop(columns="province")
normalized_wine_region_df = normalized_wine_region_df.merge(region, how="inner", left_on="region", right_on="region").rename(columns={"index": "region_id"}).drop(columns="region")
normalized_wine_region_df = normalized_wine_region_df.reset_index()

normalized_wine_region_df["id"] = normalized_wine_region_df["index"]+1
normalized_wine_region_df = normalized_wine_region_df.drop(columns="index")
# normalized_wine_region_df = normalized_wine_region_df.set_index("id")
normalized_wine_region_df.head()

   country_id  province_id  region_id  id
0           1           30          8   1
1           1           30         28   2
2           1           30        516   3
3           1           30        568   4
4           1           30        574   5

In [27]:
#Just checking if the table contained all the unique items from the tables below

print(len(wine_region_df["country"].unique()))
print(len(wine_region_df["province"].unique()))
print(len(wine_region_df["region"].unique()))
print("---")
print(normalized_wine_region_df["country_id"].max())
print(normalized_wine_region_df["province_id"].max())
print(normalized_wine_region_df["region_id"].max())

7
65
1204
---
7
65
1204

In [28]:
clean_wine_db_normalized_df = clean_wine_db_df
clean_wine_db_normalized_df["wine_region_id"] = ""
clean_wine_db_normalized_df.head()
# 7th Table: NORMALIZED DATA

,level_0,country_id,region_id,province_id,winery_id,variety_id,vineyard_id,title,points,price,review,index,wine_region_id
0,0,7,529,31,9759,348,26729,St. Julian 2013 Reserve Late Harvest Riesling ...,87,13.0,"Pineapple rind, lemon pith and orange blossom ...",1,
1,1,7,387,9,5227,348,26729,Geyser Peak 1998 Reserve Late Harvest Riesling...,86,19.0,"Even before you smell it, you can tell this is...",2,
2,2,7,276,64,3302,348,26729,Covey Run 2008 Reserve Late Harvest Riesling (...,85,12.0,Despite the reserve and late harvest designati...,3,
3,3,7,716,9,8665,87,26729,NaN,87,36.0,"Very sweet, with honey-rich apricot, tangerine...",4,
4,4,7,488,64,7,488,26729,14 Hands 2015 Reserve Late Harvest Viognier (H...,88,22.0,The aromas are somewhat light considering the ...,5,

## Código aplicado para crear region, province, contry, ultra-normalized table

In [29]:
pd.set_option("max_rows", 15)

In [ ]:
for x in range(1,len(normalized_wine_region_df)):
    print(f"processing registry {x}")
    try:
        for i in range(len(clean_wine_db_normalized_df)):
            if normalized_wine_region_df["country_id"][x] == clean_wine_db_normalized_df["country_id"][i] and normalized_wine_region_df["province_id"][x] == clean_wine_db_normalized_df["province_id"][i] and normalized_wine_region_df["region_id"][x] == clean_wine_db_normalized_df["region_id"][i]:
                clean_wine_db_normalized_df["wine_region_id"][i] = normalized_wine_region_df["id"][x]
    except:
        print(f"COULDN'T MAKE registry {x}")
            
clean_wine_db_normalized_df.head()

processing registry 1

<ipython-input-30-6be4de439a43>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_wine_db_normalized_df["wine_region_id"][i] = normalized_wine_region_df["id"][x]

processing registry 2
processing registry 3
processing registry 4
processing registry 5
processing registry 6
processing registry 7
processing registry 8
processing registry 9
processing registry 10
processing registry 11
processing registry 12
processing registry 13
processing registry 14
processing registry 15
processing registry 16
processing registry 17
processing registry 18
processing registry 19
processing registry 20
processing registry 21
processing registry 22
processing registry 23
processing registry 24
processing registry 25
processing registry 26
processing registry 27
processing registry 28
processing registry 29
processing registry 30
processing registry 31
processing registry 32
processing registry 33
processing registry 34
processing registry 35
processing registry 36
processing registry 37
processing registry 38
processing registry 39
processing registry 40
processing registry 41
processing registry 42
processing registry 43
processing registry 44
processing registry 45

In [ ]:
#Normalizing data
clean_wine_db_normalized_df = clean_wine_db_normalized_df.copy().drop(columns=["country_id", "region_id", "province_id"])

# Ordering Columns
clean_wine_db_normalized_df= clean_wine_db_normalized_df[["wine_region_id","winery_id","variety_id","vineyard_id","title",
              "points","price","review"]]
clean_wine_db_normalized_df_BACKUP = clean_wine_db_normalized_df

In [ ]:
clean_wine_db_normalized_df_BACKUP.head()

In [ ]:
clean_wine_db_normalized_df_BACKUP.iloc[4293:4295]

In [ ]:
# clean_wine_db_normalized_df.loc[pd.DataFrame.isnull(clean_wine_db_normalized_df["wine_region_id"])==True]
# clean_wine_db_normalized_df_BACKUP.iloc[4293,0]

clean_wine_db_normalized_df_BACKUP.loc[clean_wine_db_normalized_df_BACKUP["wine_region_id"]=='']

In [ ]:
clean_wine_db_normalized_df_BACKUP.to_csv("clean_wine_db_normalized_df.csv")
# clean_wine_db_normalized_df.head()

In [ ]:
clean_wine_db_normalized_df.iloc[16069:16070]

# 7th Table: ULTRA-NORMALIZED TABLE (optional, instead of previous 7th Table)

In [ ]:
# clean_wine_db_normalized_df.loc[clean_wine_db_normalized_df["wine_region_id"]==0]


is_null_df = clean_wine_db_normalized_df_backup.loc[pd.DataFrame.isnull(clean_wine_db_normalized_df_backup["wine_region_id"])==True]
is_null_df = is_null_df.reset_index()
pd.set_option("max_rows", None)
is_null_df.head()

In [ ]:
missing_rows=[]

for x in range(len(is_null_df)):
    print(f'processing registry {x}')
    for i in range(len(clean_wine_db_df)):
        if is_null_df["review"][x] == clean_wine_db_df["review"][i]:
            missing_rows.append(clean_wine_db_df["index"][i])
            
missing_rows

In [ ]:
clean_wine_db_df.iloc[16069,0]

In [ ]:
normalized_wine_region_df

In [ ]:
normalized_wine_region_df.loc[(normalized_wine_region_df["country_id"]==1) & (normalized_wine_region_df["region_id"]==8) & (normalized_wine_region_df["province_id"]==30)]

In [ ]:
# test = {}

for x in range(len(missing_rows)):
    if x == 0:
        missing_row = clean_wine_db_df.loc[clean_wine_db_df["index"]==f'{missing_rows[x]}']
        test = pd.DataFrame(missing_row)
    else:
        add_row = clean_wine_db_df.loc[clean_wine_db_df["index"]==f'{missing_rows[x]}']
        test2 = pd.DataFrame(add_row)
        test.update(test2)
        
test2

In [ ]:
test = pd.isnull(clean_wine_db_normalized_df["wine_region_id"]) 
test.value_counts()
# clean_wine_db_normalized_df[test]

In [ ]:
file="../../clean_wine_db_normalized_df.csv"
clean_wine_db_normalized_df_backup=pd.read_csv(file,  index_col=0)
# clean_wine_db_normalized_df_backup["wine_region_id"] = clean_wine_db_normalized_df_backup["wine_region_id"].astype(int)
clean_wine_db_normalized_df_backup.head()

In [ ]:
clean_wine_db_normalized_df_backup.sort_values(by="wine_region_id", ascending=False)

### Test between ultra normalized df and the country, province and region tables

In [ ]:
clean_wine_db_normalized_df.iloc[16069:16070]

In [ ]:
clean_wine_db_df.iloc[16069:16070]

In [ ]:
wine_region_df.iloc[1194:1195]

In [ ]:
wine_region_df.iloc[0:1]

In [ ]:
wine_region_df.loc[wine_region_df["province"]=="Mendoza Province"]

In [ ]:
clean_wine_db1.loc[clean_wine_db1["title"]=="Lamadrid 2012 Single Vineyard Cabernet Sauvignon (Agrelo)"]

In [ ]:
wine_region_df.loc[(wine_region_df["country"]=="Argentina")]

In [ ]:
print(country.loc[country["index"]==1])
print(region.loc[region["index"]==8])
print(province.loc[province["index"]==30])